### ISSUE TITLE
Portraits de 2001

### ISSUE THREAD

**Issue by Ipuch** [anisayari/MissFranceByRobot#10]
Si quelqu'un veut extraire les visages de 2001, c'est dispo ici.
https://www.youtube.com/watch?v=PkkRR18GLm8
A+

**Comment by Super-Botman** [comment]
la video a été strike par tf1

**Comment by Ipuch** [comment]
Je suis au Canada, ça passe très bien. Avec un vpn ça devrait le faire.

**Comment by Super-Botman** [comment]
ok
