### ISSUE TITLE
notebook sous windows ...

### ISSUE THREAD

**Issue by surfufu** [anisayari/MissFranceByRobot#23]
Hello c'est SurFufu ;) DrJVTek ... bref tu sais qui je suis ... 

dans ton readme tu devrais mettre que sous windows il faut faire : 

"python -m notebook"

car 

"jupyter notebook"  ne fonctionne pas sous windows

**Comment by Super-Botman** [comment]
ok

**Comment by anisayari** [comment]
La commande `jupyter notebook` fonctionne bien sous python.

https://jupyter.org/install
