### ISSUE TITLE
Photos de 2012

### ISSUE THREAD

**Issue by Ipuch** [anisayari/MissFranceByRobot#9]
Hello,
J'ai pas le temps de les ajouter moi-même. Je laisse le lien pour les gars disponibles.

https://www.public.fr/Dossiers/Election-de-Miss-France-2012/Les-news-sur-l-election-de-Miss-France-2012/Photos-Miss-France-2012-votez-pour-votre-candidate-preferee-146737

Bonne soirée les gars !

**Comment by Larsluph** [comment]
Je m'en suis chargé ! Merci pour la source ;)

**Comment by Super-Botman** [comment]
On peut fermer l'issue ducoup ?
